/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELENGHT 256
#define N 5

typedef char nome[MAXNAMELENGHT];

struct Input_conta {
	nome fileName;
	nome linea;
};
typedef struct Input_conta Input_conta;

struct Imput_lista {
	nome dirName;
	char carattere;
};
typedef struct Imput_lista Imput_lista;

struct Output {
	nome lista[N];
};
typedef struct Output Output;

#define EIGHTPROG 0x20000008
#define EIGHTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CONTA_OCCORRENZE 1
extern  int * conta_occorrenze_1(Input_conta *, CLIENT *);
extern  int * conta_occorrenze_1_svc(Input_conta *, struct svc_req *);
#define LISTA_FILE_CARATTERE 2
extern  Output * lista_file_carattere_1(Input_lista *, CLIENT *);
extern  Output * lista_file_carattere_1_svc(Input_lista *, struct svc_req *);
extern int eightprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONTA_OCCORRENZE 1
extern  int * conta_occorrenze_1();
extern  int * conta_occorrenze_1_svc();
#define LISTA_FILE_CARATTERE 2
extern  Output * lista_file_carattere_1();
extern  Output * lista_file_carattere_1_svc();
extern int eightprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nome (XDR *, nome);
extern  bool_t xdr_Input_conta (XDR *, Input_conta*);
extern  bool_t xdr_Imput_lista (XDR *, Imput_lista*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_nome ();
extern bool_t xdr_Input_conta ();
extern bool_t xdr_Imput_lista ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
