Vagrant.configure("2") do |config| 
   config.vm.box = "debian/bullseye64"

   config.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
   end

   config.vm.define "Router1" do |machine|
      machine.vm.hostname = "Router1"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
   end


   config.vm.define "Router2" do |machine|
      machine.vm.hostname = "Router2"
      machine.vm.network "private_network", virtualbox__intnet: "LAN2", auto_config: false
      machine.vm.network "private_network", virtualbox__intnet: "LAN3", auto_config: false
   end

   config.vm.define "Client" do |machine|
      machine.vm.hostname = "Client"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
   end
      
   config.vm.define "Server" do |machine|
      machine.vm.hostname = "Server"
      machine.vm.network "private_network", virtualbox__intnet: "LAN3", auto_config: false
   end

   config.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
   end
end
