---
- hosts: all
  become: true
  tasks:

      - name: "Add the user'johnd'"
        ansible.builtin.user:
          name: johnd
          comment: John Doe

      - name: "Impostare nuova password a John Doe"
        ansible.builtin.user:
          name: johnd 
          password: !
                  # Da inserire l'hash della password desiderata ... 

      - name: "Disabilitare John Doe tra 180 giorni"
        ansible.builtin.user:
          name: johnd
          expires: 1699364457  
                   # echo $(( $(date +%s) + 180 * 60 * 60 * 24 ))

      - name: "Creare automaticamente la home directory a John Doe"
        ansible.builtin.user:
          name: johnd
          create_home: true
          state: present 
          home: /home/johnd
 
      - name: "Creare il gruppo johnd"
        ansible.builtin.group:
          name: johnd

      - name: "Aggiungiamo John Doe a johnd"
        ansible.builtin.user:
          name: johnd
          group: johnd
