---
- hosts: all
  become: true
  tasks:
 
# Se ho ansible.posix
#   - name: Upload ssh public key in Authorized_key
#     ansible.posix.authorized_key:
#       user: johnd
#       state: present
#       key: "{{ lookup('file', '~/.ssh/id_rsa_ansible.pub') }}"

# Altrimenti
    - name: "Installo la cartella .ssh su varant"
      ansible.builtin.file:
        path: /home/johnd/.ssh
        state: directory
        mode: '0755'
        owner: johnd
        group: johnd

    - name: "Aggiungo le regole dal Control Node al Managed Node"
      ansible.builtin.copy:
        src: /home/LABS/s0000971455/.ssh/id_rsa_ansible.pub
        dest: /home/johnd/.ssh
        mode: '0755'
        owner: johnd
        group: johnd
