---
- hosts: all
  tasks:

     - name: Schedule backup
       ansible.builtin.cron:
         name: "backup selected files"
         minute: "*/2"
         weekday: "1-5"
         month: "1-7,9-12"
         job: "/usr/bin/copy.sh 2>/dev/null >/dev/null"

# MODO 1 - disabilitare job
#     - name: Disable 'Schedule backup'
#       ansible.builtin.cron:
#         name: "backup selected files"
#         state: present
#         disabled: true

# MODO 2 - elimare job
#     - name: Delete 'Schedule backup'
#       ansible.builtin.cron:
#         name: "backup selected files"
#         state: absent
