/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
//#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include <rpc/pmap_clnt.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELENGHT 20
#define N 6

typedef char nome[MAXNAMELENGHT];

struct Riga {
	nome id;
	nome tipo;
	nome partenza;
	nome arrivo;
	int hh;
	int mm;
	int ritardo;
	nome audio;
};
typedef struct Riga Riga;

struct Output {
	nome corse[N];
	int dimL;
};
typedef struct Output Output;

struct Input {
	nome id;
	int newRitardo;
};
typedef struct Input Input;

#define EIGHTPROG 0x20000008
#define EIGHTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA_LISTA 1
extern  Output * visualizza_lista_1(char *, CLIENT *);
extern  Output * visualizza_lista_1_svc(char *, struct svc_req *);
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1(Input *, CLIENT *);
extern  int * esprimi_voto_1_svc(Input *, struct svc_req *);
extern int eightprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA_LISTA 1
extern  Output * visualizza_lista_1();
extern  Output * visualizza_lista_1_svc();
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int eightprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nome (XDR *, nome);
extern  bool_t xdr_Riga (XDR *, Riga*);
extern  bool_t xdr_Output (XDR *, Output*);
extern  bool_t xdr_Input (XDR *, Input*);

#else /* K&R C */
extern bool_t xdr_nome ();
extern bool_t xdr_Riga ();
extern bool_t xdr_Output ();
extern bool_t xdr_Input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
