/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROPOSTA_H_RPCGEN
#define _PROPOSTA_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include <rpc/pmap_clnt.h>
#include <dirent.h>
#include <sys/stat.h>


struct OutputFileScan {
	int num_char;
	int num_parole;
	int num_linee;
	int errorCode;
};
typedef struct OutputFileScan OutputFileScan;
#ifdef __cplusplus
extern "C" bool_t xdr_OutputFileScan(XDR *, OutputFileScan*);
#elif __STDC__
extern  bool_t xdr_OutputFileScan(XDR *, OutputFileScan*);
#else /* Old Style C */
bool_t xdr_OutputFileScan();
#endif /* Old Style C */


struct IntputDirScan {
	char dirName[256];
	int num_soglia;
};
typedef struct IntputDirScan IntputDirScan;
#ifdef __cplusplus
extern "C" bool_t xdr_IntputDirScan(XDR *, IntputDirScan*);
#elif __STDC__
extern  bool_t xdr_IntputDirScan(XDR *, IntputDirScan*);
#else /* Old Style C */
bool_t xdr_IntputDirScan();
#endif /* Old Style C */


struct FileName {
	char name[256];
};
typedef struct FileName FileName;
#ifdef __cplusplus
extern "C" bool_t xdr_FileName(XDR *, FileName*);
#elif __STDC__
extern  bool_t xdr_FileName(XDR *, FileName*);
#else /* Old Style C */
bool_t xdr_FileName();
#endif /* Old Style C */


struct OutputDirScan {
	FileName names[8];
	int intero;
};
typedef struct OutputDirScan OutputDirScan;
#ifdef __cplusplus
extern "C" bool_t xdr_OutputDirScan(XDR *, OutputDirScan*);
#elif __STDC__
extern  bool_t xdr_OutputDirScan(XDR *, OutputDirScan*);
#else /* Old Style C */
bool_t xdr_OutputDirScan();
#endif /* Old Style C */


#define OPSPROG ((rpc_uint)0x20000013)
#define OPSVERS ((rpc_uint)1)

#ifdef __cplusplus
#define FILE_SCAN ((rpc_uint)1)
extern "C" OutputFileScan * file_scan_1(char **, CLIENT *);
extern "C" OutputFileScan * file_scan_1_svc(char **, struct svc_req *);
#define DIR_SCAN ((rpc_uint)2)
extern "C" OutputDirScan * dir_scan_1(IntputDirScan *, CLIENT *);
extern "C" OutputDirScan * dir_scan_1_svc(IntputDirScan *, struct svc_req *);

#elif __STDC__
#define FILE_SCAN ((rpc_uint)1)
extern  OutputFileScan * file_scan_1(char **, CLIENT *);
extern  OutputFileScan * file_scan_1_svc(char **, struct svc_req *);
#define DIR_SCAN ((rpc_uint)2)
extern  OutputDirScan * dir_scan_1(IntputDirScan *, CLIENT *);
extern  OutputDirScan * dir_scan_1_svc(IntputDirScan *, struct svc_req *);

#else /* Old Style C */
#define FILE_SCAN ((rpc_uint)1)
extern  OutputFileScan * file_scan_1();
extern  OutputFileScan * file_scan_1_svc();
#define DIR_SCAN ((rpc_uint)2)
extern  OutputDirScan * dir_scan_1();
extern  OutputDirScan * dir_scan_1_svc();
#endif /* Old Style C */

#endif /* !_PROPOSTA_H_RPCGEN */
