Vagrant.configure("2") do |config| 
   config.vm.box = "debian/bullseye64"

   config.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
   end

   config.vm.define "agent" do |machine|
      machine.vm.hostname = "agent"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    end
  
    config.vm.define "manager" do |machine|
      machine.vm.hostname = "manager"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
    end

   config.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
   end
end
