# Sec Lab Web Challenges Container
#

FROM alpine:3.11
MAINTAINER  Andrea Melis <a.melis@unibo.it>

RUN apk --no-cache add python py-lxml \
	&& rm -rf /var/cache/apk/* 
RUN apk --no-cache add shadow

RUN useradd -ms /bin/bash seclabexamjan


WORKDIR /tmp
RUN wget https://gitlab.com/wild_boar/labsec_course/-/raw/master/web_challenges/web.py

#ADD web.py /web.py

EXPOSE 8000

CMD ["python", "web.py"]
