- name: install LDAP-utils
  ansible.builtin.apt:
    update-cache: yes

- name: install LDAP-utils
  ansible.builtin.apt:
    pkg:
    - ldap-utils
    state: present

- name: install ldap lib
  ansible.builtin.apt:
    pkg:
    - libnss-ldap
    - libpam-ldap
    - nscd
    state: present

- name: Copy LDAP conf file
  ansible.builtin.copy:
    src: config_files.tar
    dest: /home/vagrant/config_files.tar
    owner: vagrant
    group: vagrant
    mode: 0664
  notify: set ldap conf

- name: Copy LDAP conf script
  ansible.builtin.copy:
    src: conf_ldap.sh
    dest: /home/vagrant/conf_ldap.sh
    owner: vagrant
    group: vagrant
    mode: 0744
