/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proposta.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Output *
classifica_giudici_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static Output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CLASSIFICA_GIUDICI, xdr_void, argp, xdr_Output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
esprimi_voto_1(argp, clnt)
	InputEsprimiVoto *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ESPRIMI_VOTO, xdr_InputEsprimiVoto, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
