/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proposta.h"

bool_t
xdr_nome(xdrs, objp)
	XDR *xdrs;
	nome objp;
{

	if (!xdr_vector(xdrs, (char *)objp, MAXNAMELENGHT, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_InputEsprimiVoto(xdrs, objp)
	XDR *xdrs;
	InputEsprimiVoto *objp;
{

	if (!xdr_nome(xdrs, objp->candidato))
		return (FALSE);
	if (!xdr_nome(xdrs, objp->operazione))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Giudice(xdrs, objp)
	XDR *xdrs;
	Giudice *objp;
{

	if (!xdr_nome(xdrs, objp->giudice))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->punteggio_tot))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Output(xdrs, objp)
	XDR *xdrs;
	Output *objp;
{

	if (!xdr_int(xdrs, &objp->num_giudici))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->giudici, N, sizeof(Giudice), (xdrproc_t)xdr_Giudice))
		return (FALSE);
	return (TRUE);
}
