/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proposta.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

OutputFileScan *
file_scan_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static OutputFileScan clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, FILE_SCAN, xdr_wrapstring, argp, xdr_OutputFileScan, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

OutputDirScan *
dir_scan_1(argp, clnt)
	IntputDirScan *argp;
	CLIENT *clnt;
{
	static OutputDirScan clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DIR_SCAN, xdr_IntputDirScan, argp, xdr_OutputDirScan, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
