/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_LEN 12
#define N 10

typedef char nome[MAX_LEN];

struct Output {
	nome ids[6];
};
typedef struct Output Output;

#define EIGHTPROG 0x20000008
#define EIGHTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA_PRENOTAZIONI 1
extern  Output * visualizza_prenotazioni_1(char *, CLIENT *);
extern  Output * visualizza_prenotazioni_1_svc(char *, struct svc_req *);
#define ELIMINA_MONOPATTINO 2
extern  int * elimina_monopattino_1(char *, CLIENT *);
extern  int * elimina_monopattino_1_svc(char *, struct svc_req *);
extern int eightprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA_PRENOTAZIONI 1
extern  Output * visualizza_prenotazioni_1();
extern  Output * visualizza_prenotazioni_1_svc();
#define ELIMINA_MONOPATTINO 2
extern  int * elimina_monopattino_1();
extern  int * elimina_monopattino_1_svc();
extern int eightprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nome (XDR *, nome);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_nome ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
