/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SALA_H_RPCGEN
#define _SALA_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include <rpc/pmap_clnt.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>

#define LUNGHFILA 7
#define NUMFILE 10

struct Input {
	char tipo;
	int fila;
	int colonna;
};
typedef struct Input Input;
#ifdef __cplusplus
extern "C" bool_t xdr_Input(XDR *, Input*);
#elif __STDC__
extern  bool_t xdr_Input(XDR *, Input*);
#else /* Old Style C */
bool_t xdr_Input();
#endif /* Old Style C */


struct Fila {
	char posto[LUNGHFILA];
};
typedef struct Fila Fila;
#ifdef __cplusplus
extern "C" bool_t xdr_Fila(XDR *, Fila*);
#elif __STDC__
extern  bool_t xdr_Fila(XDR *, Fila*);
#else /* Old Style C */
bool_t xdr_Fila();
#endif /* Old Style C */


struct Sala {
	Fila fila[NUMFILE];
};
typedef struct Sala Sala;
#ifdef __cplusplus
extern "C" bool_t xdr_Sala(XDR *, Sala*);
#elif __STDC__
extern  bool_t xdr_Sala(XDR *, Sala*);
#else /* Old Style C */
bool_t xdr_Sala();
#endif /* Old Style C */


#define SALA ((rpc_uint)0x20000013)
#define SALAVERS ((rpc_uint)1)

#ifdef __cplusplus
#define PRENOTA_POSTAZIONE ((rpc_uint)1)
extern "C" int * prenota_postazione_1(Input *, CLIENT *);
extern "C" int * prenota_postazione_1_svc(Input *, struct svc_req *);
#define VISUALIZZA_STATO ((rpc_uint)2)
extern "C" Sala * visualizza_stato_1(void *, CLIENT *);
extern "C" Sala * visualizza_stato_1_svc(void *, struct svc_req *);

#elif __STDC__
#define PRENOTA_POSTAZIONE ((rpc_uint)1)
extern  int * prenota_postazione_1(Input *, CLIENT *);
extern  int * prenota_postazione_1_svc(Input *, struct svc_req *);
#define VISUALIZZA_STATO ((rpc_uint)2)
extern  Sala * visualizza_stato_1(void *, CLIENT *);
extern  Sala * visualizza_stato_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define PRENOTA_POSTAZIONE ((rpc_uint)1)
extern  int * prenota_postazione_1();
extern  int * prenota_postazione_1_svc();
#define VISUALIZZA_STATO ((rpc_uint)2)
extern  Sala * visualizza_stato_1();
extern  Sala * visualizza_stato_1_svc();
#endif /* Old Style C */

#endif /* !_SALA_H_RPCGEN */
