/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sala.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
prenota_postazione_1(argp, clnt)
	Input *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, PRENOTA_POSTAZIONE, xdr_Input, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

Sala *
visualizza_stato_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static Sala clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, VISUALIZZA_STATO, xdr_void, argp, xdr_Sala, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
