/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_nome (XDR *xdrs, nome objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InputFile (XDR *xdrs, InputFile *objp)
{
	register int32_t *buf;

	 if (!xdr_nome (xdrs, objp->fileName))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->line))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InputDir (XDR *xdrs, InputDir *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_nome (xdrs, objp->dirName))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prefisso, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->listaNomi, N,
		sizeof (nome), (xdrproc_t) xdr_nome))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->errNum))
		 return FALSE;
	return TRUE;
}
