/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include <rpc/pmap_clnt.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>

#define MAXNAMELENGHT 20
#define N 6

typedef char nome[MAXNAMELENGHT];
#ifdef __cplusplus
extern "C" bool_t xdr_nome(XDR *, nome);
#elif __STDC__
extern  bool_t xdr_nome(XDR *, nome);
#else /* Old Style C */
bool_t xdr_nome();
#endif /* Old Style C */


struct Output {
	nome lista[N];
	int errCode;
};
typedef struct Output Output;
#ifdef __cplusplus
extern "C" bool_t xdr_Output(XDR *, Output*);
#elif __STDC__
extern  bool_t xdr_Output(XDR *, Output*);
#else /* Old Style C */
bool_t xdr_Output();
#endif /* Old Style C */


#define EIGHTPROG ((rpc_uint)0x20000008)
#define EIGHTVERS ((rpc_uint)1)

#ifdef __cplusplus
#define VISUALIZZA_PRENOTAZIONE ((rpc_uint)1)
extern "C" Output * visualizza_prenotazione_1(char *, CLIENT *);
extern "C" Output * visualizza_prenotazione_1_svc(char *, struct svc_req *);
#define ELIMINA_PRENOTAZIONI ((rpc_uint)2)
extern "C" int * elimina_prenotazioni_1(char *, CLIENT *);
extern "C" int * elimina_prenotazioni_1_svc(char *, struct svc_req *);

#elif __STDC__
#define VISUALIZZA_PRENOTAZIONE ((rpc_uint)1)
extern  Output * visualizza_prenotazione_1(char *, CLIENT *);
extern  Output * visualizza_prenotazione_1_svc(char *, struct svc_req *);
#define ELIMINA_PRENOTAZIONI ((rpc_uint)2)
extern  int * elimina_prenotazioni_1(char *, CLIENT *);
extern  int * elimina_prenotazioni_1_svc(char *, struct svc_req *);

#else /* Old Style C */
#define VISUALIZZA_PRENOTAZIONE ((rpc_uint)1)
extern  Output * visualizza_prenotazione_1();
extern  Output * visualizza_prenotazione_1_svc();
#define ELIMINA_PRENOTAZIONI ((rpc_uint)2)
extern  int * elimina_prenotazioni_1();
extern  int * elimina_prenotazioni_1_svc();
#endif /* Old Style C */

#endif /* !_RPC_XFILE_H_RPCGEN */
