/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_nome(xdrs, objp)
	XDR *xdrs;
	nome objp;
{

	if (!xdr_vector(xdrs, (char *)objp, MAXNAMELENGHT, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Output(xdrs, objp)
	XDR *xdrs;
	Output *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->lista, N, sizeof(nome), (xdrproc_t)xdr_nome))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->errCode))
		return (FALSE);
	return (TRUE);
}
