package esame.hibernate;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.hibernate.criterion.Restrictions;
import org.hibernate.dialect.Dialect;
import org.hibernate.jdbc.util.FormatStyle;
import org.hibernate.jdbc.util.Formatter;

import esame.hibernate.beans.Due;
import esame.hibernate.beans.Tre;
import esame.hibernate.beans.Uno;

public class HibernateTest {

	private static Configuration configuration;
	private static SessionFactory sessionFactory;

	public static void main(String[] args) {
		configuration = new Configuration().configure();
		sessionFactory = configuration.buildSessionFactory();
		
		//DA ELIMINARE!
		generateDdlStatements();
		
		//JDBC DROP AND CREATE
		Connection conn = null;
		Statement st = null;
		try {
			// DB2 dal LAB
			// Class.forName("COM.ibm.db2.jdbc.app.DB2Driver").newInstance();
			// String url = "jdbc:db2:tw_stud";

			// DB2 da remoto
			Class.forName("com.ibm.db2.jcc.DB2Driver");
			String url = "jdbc:db2://diva.deis.unibo.it:50000/tw_stud";
			
			String username = "00718825";
			String password = "*";

			conn = DriverManager.getConnection(url, username, password);
			//Imposto la transazione se non riesco a creare i mapping a causa dei riferimenti
			// conn.setAutoCommit(false);
			st = conn.createStatement();

			List<String> queries = new ArrayList<>();

			
			queries.add("drop table uno_due");
			queries.add("drop table uno");
			queries.add("drop table due");
			queries.add("drop table tre");
			for (String query : queries) {
				System.out.println(query);
				try {
					st.executeUpdate(query);
				} catch (Exception e) {
					//Non faccio nulla perchè un'eccezione a questo punto significa che la tabella non esisteva, vado avanti
				}
			}


			queries = new ArrayList<>();
			queries.add("create table uno (id integer generated by default as identity, uno1 varchar(255), uno2 varchar(255), primary key (id))");
			queries.add("create table due (id integer generated by default as identity, due1 varchar(255), due2 varchar(255), primary key (id))");
			queries.add("create table tre (id integer generated by default as identity, tre1 varchar(255), tre2 varchar(255), iddue integer, primary key (id))");
			queries.add("create table uno_due (iduno integer not null, iddue integer not null, primary key (iddue, iduno))");
			for (String query : queries) {
				System.out.println(query);
				st.executeUpdate(query);
			}
			// conn.commit();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			try {
				if (st != null)
					st.close();
				if (conn != null)
					conn.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
		//JDBC DROP AND CREATE
		
		
		//HIBERNATE DROP AND CREATE
		Session session = null;
		Transaction tx = null;
		try {
			session = sessionFactory.openSession();
			tx = session.beginTransaction();

			List<String> queries = new ArrayList<>();

			
			queries.add("drop table uno_due");
			queries.add("drop table uno");
			queries.add("drop table due");
			queries.add("drop table tre");
			for (String query : queries) {
				try {
					session.createSQLQuery(query).executeUpdate();
				} catch (Exception e) {
					//Non faccio nulla perchè un'eccezione a questo punto significa che la tabella non esisteva, vado avanti
				}
			}
			
			queries = new ArrayList<>();
			queries.add("create table uno (id integer generated by default as identity, uno1 varchar(255), uno2 varchar(255), primary key (id))");
			queries.add("create table due (id integer generated by default as identity, due1 varchar(255), due2 varchar(255), primary key (id))");
			queries.add("create table tre (id integer generated by default as identity, tre1 varchar(255), tre2 varchar(255), iddue integer, primary key (id))");
			queries.add("create table uno_due (iduno integer not null, iddue integer not null, primary key (iddue, iduno))");
			
			
			for (String query : queries) {
				session.createSQLQuery(query).executeUpdate();
			}

			tx.commit();
		} catch (Exception e) {
			if (tx != null) {
				try {
					tx.rollback();
				} catch (Exception e2) {
					e2.printStackTrace();
				}
			}
			e.printStackTrace();
		} finally {
			session.close();
		}
		//HIBERNATE DROP AND CREATE
		
		
		//AGGIUNGO TUPLE
//		Session session = null;
//		Transaction tx = null;
		session = null;
		try {
			session = sessionFactory.openSession();
			tx = session.beginTransaction();
			
			
			Uno uno1 = new Uno("prova1", "prova2");
			Uno uno2 = new Uno("ciao1", "ciao2");
			
			Due due1 = new Due("boh1", "boh2");
			Due due2 = new Due("foo1", "foo2");
			
			Tre tre1 = new Tre("bar1", "bar2");
			Tre tre2 = new Tre("topolino1", "topolino2");
			
			uno1.getDues().add(due1);
			uno2.getDues().add(due1);
			uno2.getDues().add(due2);
			
			due1.getUnos().add(uno1);
			due1.getUnos().add(uno2);
			due2.getUnos().add(uno2);
			
			due1.getTres().add(tre1);
			due2.getTres().add(tre2);
			
			tre1.setDue(due1);
			tre2.setDue(due2);
			
			
			session.persist(uno1);
			session.persist(uno2);
			session.persist(due1);
			session.persist(due2);
			session.persist(tre1);
			session.persist(tre2);
			
			
			tx.commit();
		} catch (Exception e1) {
			if (tx != null) {
				try {
					tx.rollback();
				} catch (Exception e2) {
					e2.printStackTrace();
				}
			}
			e1.printStackTrace();
		} finally {
			session.close();
		}
		
		
		printRequestedQueries(new PrintWriter(System.out)); //Inserisci qui il nome del file di output
	}

	//DA ELIMINARE!
	private static void generateDdlStatements() {
		System.out.println("\n\n----------------- DDL STATEMENTS ------------------------------------");
		{
			Dialect dialect = Dialect.getDialect(configuration.getProperties());
			String[] createSQL = configuration.generateSchemaCreationScript(dialect);
			String[] dropSQL = configuration.generateDropSchemaScript(dialect);

			Formatter formatter = FormatStyle.DDL.getFormatter();
			try (PrintWriter writer = new PrintWriter(new FileOutputStream("ddl.txt"))) {
				for (String string : dropSQL) {
					System.out.println(formatter.format(string)+";");
					writer.println("queries.add(\""+string+"\");");
				}
				System.out.println("\n\n\n");
				writer.println("\n\n\n");
				for (String string : createSQL) {
					System.out.println(formatter.format(string) + ";");
					writer.println("queries.add(\""+string+"\");");
				}
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			}
		}
	}
	
	public static void printRequestedQueries(PrintWriter out) {
		//Query richieste:
		Session session = null;
		try {
			session = sessionFactory.openSession();
			
			//SQL
			SQLQuery query = session.createSQLQuery("SELECT due.due1 as due1, COUNT(*) AS NUM from uno, due, uno_due where uno.id = uno_due.iduno and due.id = uno_due.iddue group by due.due1");
			query.setResultTransformer(Criteria.ALIAS_TO_ENTITY_MAP);
			List result = query.list();
			out.println("Query 1");
			for (Object o : result) {
				Map map = (Map) o;
				out.println(map.get("DUE1") + " e' associato a "+map.get("NUM")+" oggetti uno");
			}
			//HQL
			Query query2 = session.createQuery("from "+Due.class.getSimpleName());
			List<Due> result2 = query2.list();
			out.println("Query 1");
			for (Due due : result2) {
				out.println(due.getDue1()+" e' associato a "+due.getUnos().size()+" oggetti uno");
			}
			//Criteria
			Criteria criteria = session.createCriteria(Due.class);
			//criteria.add(Restrictions.eq("lastName", "Gialli"));
			List<Due> result3 = criteria.list();
			out.println("Query 1");
			for (Due due : result3) {
				out.println(due.getDue1()+" e' associato a "+due.getUnos().size()+" oggetti uno");
			}
			
			
			
			//SQL
			SQLQuery query3 = session.createSQLQuery("SELECT * FROM uno").addEntity(Uno.class);
			List<Uno> result4 = query3.list();
			out.println("Query 2");
			for (Uno uno : result4) {
				out.println(uno.getUno1() + " contiene:");
				Set<Tre> tres = new HashSet<>();
				for (Due due : uno.getDues()) {
					//HashSet non aggiunge se già presente
					due.getTres().stream().forEach(tre -> tres.add(tre));
				}
				
				//Stampa
				for (Tre tre : tres) {
					out.println(tre.getTre1()+", "+tre.getTre2());
				}
				out.println("");
			}
			//HQL
			Query query4 = session.createQuery("from "+Uno.class.getSimpleName());
			List<Uno> result5 = query4.list();
			out.println("Query 2");
			for (Uno uno : result5) {
				out.println(uno.getUno1() + " contiene:");
				Set<Tre> tres = new HashSet<>();
				for (Due due : uno.getDues()) {
					//HashSet non aggiunge se già presente
					due.getTres().stream().forEach(tre -> tres.add(tre));
				}
				
				//Stampa
				for (Tre tre : tres) {
					out.println(tre.getTre1()+", "+tre.getTre2());
				}
				out.println("");
			}
			//Criteria
			Criteria criteria2 = session.createCriteria(Uno.class);
			//criteria.add(Restrictions.eq("lastName", "Gialli"));
			List<Uno> result6 = criteria2.list();
			out.println("Query 2");
			for (Uno uno : result6) {
				out.println(uno.getUno1() + " contiene:");
				Set<Tre> tres = new HashSet<>();
				for (Due due : uno.getDues()) {
					//HashSet non aggiunge se già presente
					due.getTres().stream().forEach(tre -> tres.add(tre));
				}
				
				//Stampa
				for (Tre tre : tres) {
					out.println(tre.getTre1()+", "+tre.getTre2());
				}
				out.println("");
			}
			
			
//			Query medicoConPiuRisonanzePerFemmineQuery = session.getNamedQuery("medicoConPiuRisonanzePerFemmine");
//			String medico = (String) medicoConPiuRisonanzePerFemmineQuery.uniqueResult();
//			System.out.println(medico);

//			String sql =
//			"select P.Nome, P.Cognome from Garage G, Macchina M, Proprietario
//			P where G.id=M.garage_id and M.proprietario_id=P.id and
//			G.nomeGarage=:nomeGarage";
//			SQLQuery query = session.createSQLQuery(sql);
//			query.setParameter("nomeGarage", "g1");
//			query.setResultTransformer(Criteria.ALIAS_TO_ENTITY_MAP);
//			List data = query.list();
//			for (Object object : data) {
//			Map row = (Map) object;
//			System.out.println(row.get("Nome") + " " + row.get("Nognome"));
//			}

//			for(Object o : session.createCriteria(Commissario.class).list()){
//				System.out.println(o);
//			}
//
//			List singleResult = session.createCriteria(ConcorsoTFA.class).add(Restrictions.eq("classeConcorso", "A042")).list();
//			if (!singleResult.isEmpty()) {
//				ConcorsoTFA c = (ConcorsoTFA) singleResult.get(0);
//				System.out.println(c.getCandidati().size());
//				System.out.println(c.getCommissari().stream().map(Commissario::getNome).collect(Collectors.joining(", ")));
//			}

//			Garage garage = (Garage)
//			session.createCriteria(Garage.class).add(Restrictions.eq("nomeGarage",
//			"g1"))
//			.uniqueResult();
//			for (Macchina m : garage.getMacchine()) {
//			System.out.println(m.getProprietario().getNome() + " " +
//			m.getProprietario().getCognome());
//			}

//			HQL Query
//			Query query1 = session.createQuery("from
//			"+Corso.class.getSimpleName()+" where codice= ?");
//			int codice = 26;
//			query1.setInteger(0, codice);
//			System.out.println("Retrieving number of women attending course
//			"+codice+"...");
//			Corso c = (Corso)query1.uniqueResult();
//			if(c != null)
//			{
//			int res = 0;
//			for(Studente s : c.getStudenti())
//			{
//			if(s.getSesso().equals("F"))
//			{
//			res++;
//			}
//			}
//			if(res == 0)
//			{
//			System.out.println("No women are attending course "+codice);
//			}
//			else
//			{
//			System.out.println(res+" women are attending course "+codice);

//			System.out.println("Printing on Studentesse.txt the details of
//			the students just found...");
//			File f = new File("Studentesse.txt");
//			if(!f.exists())
//			{
//			f.createNewFile();
//			}
//			FileOutputStream fos = new FileOutputStream(f);
//			PrintWriter out = new PrintWriter(fos);
//			for(Studente s : c.getStudenti())
//			{
//			if(s.getSesso().equals("F"))
//			{
//			System.out.println(s.getNome()+" "+s.getCognome()+", Nata il
//			"+s.getData_nascita().toString());
//			out.println(s.getNome()+" "+s.getCognome()+", Nata il
//			"+s.getData_nascita().toString());
//			}
//			}
//			out.close();
//			System.out.println("Written to file!");
//			}
//			}

//			Criteria allConcorsi = session.createCriteria(Concorso.class);
//			((List<Concorso>)allConcorsi.list()).stream()
//			.filter(con -> con.getCommissari().stream()
//					.anyMatch(com -> { return com.getMatricola().equals("X0034");}))
//			.findFirst()
//			.ifPresent(con -> {System.out.println("classe: "+con.getClasseConcorso() + " partecipanti:"+con.getCandidati().size());});
//
//			 String sqlInner =
//			 "select C.matricola as matricola, count(CC.concorso_id) as count from candidato C join candidato_concorso CC on C.id=CC.candidato_id group by matricola";
//			 String sqlOuter = "select nome, cognome, count from ("+sqlInner+") as MC, candidato C where MC.matricola = C.matricola";
//			 SQLQuery query = session.createSQLQuery(sqlOuter);
//			 query.setResultTransformer(Criteria.ALIAS_TO_ENTITY_MAP);
//			 List data = query.list();
//			 BigInteger max = new BigInteger("0");
//			 String result = "Nessuno trovato";
//			 for (Object object : data) {
//				 Map row = (Map) object;
//				 if (max.compareTo((BigInteger)row.get("count"))<0) {
//					 max = (BigInteger)row.get("count");
//					 result = row.get("nome") + " " + row.get("cognome");
//				 }
//			 }
//			 System.out.println("Candidato che ha partecipato a piï¿½ concorsi: " + result);
			
			out.flush();
		} catch (Exception e1) {
			e1.printStackTrace();
		} finally {
			session.close();
		}
	}

}
