Vagrant.configure("2") do |config| 
   config.vm.box = "debian/bullseye64"

   config.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
   end

   config.vm.define "Manager" do |machine|
      machine.vm.hostname = "Manager"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
   end

   config.vm.define "Workstation1" do |machine|
      machine.vm.hostname = "Workstation1"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
   end
      
   config.vm.define "Workstation2" do |machine|
      machine.vm.hostname = "Workstation2"
      machine.vm.network "private_network", virtualbox__intnet: "LAN1", auto_config: false
   end

   config.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
   end
end
