/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pellegrino_lorenzo_0000971455_RPC_xFile.h"

bool_t
xdr_nome (XDR *xdrs, nome objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, MAXNAMELENGHT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Riga (XDR *xdrs, Riga *objp)
{
	register int32_t *buf;

	 if (!xdr_nome (xdrs, objp->Descrizione))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->Tipo))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->Data))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->Luogo))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->Disponibilita))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->Prezzo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InputBuy (XDR *xdrs, InputBuy *objp)
{
	register int32_t *buf;

	 if (!xdr_nome (xdrs, objp->Descrizione))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tiketDesiderati))
		 return FALSE;
	return TRUE;
}
