/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
//#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include <rpc/pmap_clnt.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>


#ifdef __cplusplus
extern "C" {
#endif

#define N 6

typedef char nome[256];

struct InputFile {
	nome fileName;
	nome line;
};
typedef struct InputFile InputFile;

struct InputDir {
	nome dirName;
	char prefisso[10];
};
typedef struct InputDir InputDir;

struct Output {
	nome listaNomi[N];
	int errNum;
};
typedef struct Output Output;

#define OPSPROG 0x20000013
#define OPSVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CONTA_OCCORRENZE_LINEA 1
extern  int * conta_occorrenze_linea_1(InputFile *, CLIENT *);
extern  int * conta_occorrenze_linea_1_svc(InputFile *, struct svc_req *);
#define LISTA_FILE_PREFISSO 2
extern  Output * lista_file_prefisso_1(InputDir *, CLIENT *);
extern  Output * lista_file_prefisso_1_svc(InputDir *, struct svc_req *);
extern int opsprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONTA_OCCORRENZE_LINEA 1
extern  int * conta_occorrenze_linea_1();
extern  int * conta_occorrenze_linea_1_svc();
#define LISTA_FILE_PREFISSO 2
extern  Output * lista_file_prefisso_1();
extern  Output * lista_file_prefisso_1_svc();
extern int opsprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nome (XDR *, nome);
extern  bool_t xdr_InputFile (XDR *, InputFile*);
extern  bool_t xdr_InputDir (XDR *, InputDir*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_nome ();
extern bool_t xdr_InputFile ();
extern bool_t xdr_InputDir ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
