- name: "snmpd installation"
  ansible.builtin.apt:
    name:
      - snmpd
    update_cache: yes

- name: "edit snmpd.conf"
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  notify: restart snmpd

- name: Modificare suoders per eseguire codice privilegiato
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: 'Debian-snmp ALL=(ALL) NOPASSWD:/usr/bin/cat'
    state: present
    insertafter: ^# User privilege specification$
    validate: 'visudo -cf %s'

