- name: "Crea /root/.ssh"
  ansible.builtin.file:
    owner: root
    group: root
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: "Copia chiave privata"
  become: true
  ansible.builtin.copy:
    src: id_rsa_ansible
    dest: /root/.ssh/id_rsa_ansible
    mode: '0600'
    owner: root
    group: root
  notify: Restart SSH

