---
- name: Installazione/Update di unit file di systemd --> consideriamo chronyd.service
  hosts: all
  become: true
  tasks:

  - name: Copio "chronyd.service"
    become: true
    ansible.builtin.template:
      src: /home/vagrant/../../etc/systemd/system/chronyd.service
      dest: /home/vagrant/../../etc/systemd/system/chronyd_copia.service
      owner: root
      group: root
      mode: '0644'
      remote_src: true

  - name: Modifico in modo lieve la copia di "chronyd.service" --> inserisco commento a fine file
    ansible.builtin.lineinfile:
      path: /home/vagrant/../../etc/systemd/system/chronyd_copia.service
      line: '# commento inserito con Ansible'
      insertafter: EOF
    notify:
    - Restart chronyd

  - name: Mi assicuro che la copia stia andando
    ansible.builtin.systemd:
      name: chronyd_copia.service
      state: started

  handlers:
    - name: Riavvio "chronyd.service"
      ansible.builtin.systemd:
        name: chronyd_copia.service
        daemon_reload: yes
