/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proposta.h"

bool_t
xdr_OutputFileScan(xdrs, objp)
	XDR *xdrs;
	OutputFileScan *objp;
{
	int32_t *buf;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->num_char))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->num_parole))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->num_linee))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->errorCode))
				return (FALSE);
		} else {
			IXDR_PUT_LONG(buf, objp->num_char);
			IXDR_PUT_LONG(buf, objp->num_parole);
			IXDR_PUT_LONG(buf, objp->num_linee);
			IXDR_PUT_LONG(buf, objp->errorCode);
		}
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->num_char))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->num_parole))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->num_linee))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->errorCode))
				return (FALSE);
		} else {
			objp->num_char = IXDR_GET_LONG(buf);
			objp->num_parole = IXDR_GET_LONG(buf);
			objp->num_linee = IXDR_GET_LONG(buf);
			objp->errorCode = IXDR_GET_LONG(buf);
		}
	} else {
		if (!xdr_int(xdrs, &objp->num_char))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->num_parole))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->num_linee))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->errorCode))
			return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_IntputDirScan(xdrs, objp)
	XDR *xdrs;
	IntputDirScan *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->dirName, 256, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->num_soglia))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FileName(xdrs, objp)
	XDR *xdrs;
	FileName *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->name, 256, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_OutputDirScan(xdrs, objp)
	XDR *xdrs;
	OutputDirScan *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->names, 8, sizeof(FileName), (xdrproc_t)xdr_FileName))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->intero))
		return (FALSE);
	return (TRUE);
}
