/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pellegrino_lorenzo_0000971455_RPC_xFile.h"

bool_t
xdr_nome(xdrs, objp)
	XDR *xdrs;
	nome objp;
{

	if (!xdr_vector(xdrs, (char *)objp, MAXLENGHT, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Input(xdrs, objp)
	XDR *xdrs;
	Input *objp;
{

	if (!xdr_nome(xdrs, objp->direttorio))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->carattere))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->num_occorrenze))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Output(xdrs, objp)
	XDR *xdrs;
	Output *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->files, N, sizeof(nome), (xdrproc_t)xdr_nome))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->errCode))
		return (FALSE);
	return (TRUE);
}
