/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
//#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include <rpc/pmap_clnt.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELENGHT 256
#define N 6

typedef char nome[MAXNAMELENGHT];

struct Input {
	nome dirName;
	char carattere;
	int numOcc;
};
typedef struct Input Input;

struct Output {
	nome files[N];
	int numErrore;
};
typedef struct Output Output;

#define EIGHTPROG 0x20000008
#define EIGHTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LISTA_FILE_CARATTERE 1
extern  Output * lista_file_carattere_1(Input *, CLIENT *);
extern  Output * lista_file_carattere_1_svc(Input *, struct svc_req *);
#define ELIMINA_OCCORRENZE 2
extern  int * elimina_occorrenze_1(char *, CLIENT *);
extern  int * elimina_occorrenze_1_svc(char *, struct svc_req *);
extern int eightprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LISTA_FILE_CARATTERE 1
extern  Output * lista_file_carattere_1();
extern  Output * lista_file_carattere_1_svc();
#define ELIMINA_OCCORRENZE 2
extern  int * elimina_occorrenze_1();
extern  int * elimina_occorrenze_1_svc();
extern int eightprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nome (XDR *, nome);
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_nome ();
extern bool_t xdr_Input ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
