---
- name: Enable UDP rsyslog
  lineinfile:
    path: /etc/rsyslog.conf
    state: present
    line: "{{ item }}"
  with_items:
  - 'module(load="imudp")'
  - 'input(type="imudp" port="514")'

- name: Copia della regola
  ansible.builtin.copy:
    src: regole
    dest: /etc/rsyslog.d/log_esame.conf
  notify: Restart rsyslog

