/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pellegrino_lorenzo_0000971455_RPC_xFile.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
elimina_occorrenze_1(argp, clnt)
	char *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ELIMINA_OCCORRENZE, xdr_nome, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

Output *
lista_file_carattere_1(argp, clnt)
	Input *argp;
	CLIENT *clnt;
{
	static Output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, LISTA_FILE_CARATTERE, xdr_Input, argp, xdr_Output, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
