/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PELLEGRINO_LORENZO_0000971455_RPC_XFILE_H_RPCGEN
#define _PELLEGRINO_LORENZO_0000971455_RPC_XFILE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/errno.h>
#include <rpc/pmap_clnt.h>
#include <dirent.h>
#include <sys/stat.h>
#include <string.h>

#define MAXLENGHT 256
#define N 6

typedef char nome[MAXLENGHT];
#ifdef __cplusplus
extern "C" bool_t xdr_nome(XDR *, nome);
#elif __STDC__
extern  bool_t xdr_nome(XDR *, nome);
#else /* Old Style C */
bool_t xdr_nome();
#endif /* Old Style C */


struct Input {
	nome direttorio;
	char carattere;
	int num_occorrenze;
};
typedef struct Input Input;
#ifdef __cplusplus
extern "C" bool_t xdr_Input(XDR *, Input*);
#elif __STDC__
extern  bool_t xdr_Input(XDR *, Input*);
#else /* Old Style C */
bool_t xdr_Input();
#endif /* Old Style C */


struct Output {
	nome files[N];
	int errCode;
};
typedef struct Output Output;
#ifdef __cplusplus
extern "C" bool_t xdr_Output(XDR *, Output*);
#elif __STDC__
extern  bool_t xdr_Output(XDR *, Output*);
#else /* Old Style C */
bool_t xdr_Output();
#endif /* Old Style C */


#define OPSPROG ((rpc_uint)0x20000013)
#define OPSVERS ((rpc_uint)1)

#ifdef __cplusplus
#define ELIMINA_OCCORRENZE ((rpc_uint)1)
extern "C" int * elimina_occorrenze_1(char *, CLIENT *);
extern "C" int * elimina_occorrenze_1_svc(char *, struct svc_req *);
#define LISTA_FILE_CARATTERE ((rpc_uint)2)
extern "C" Output * lista_file_carattere_1(Input *, CLIENT *);
extern "C" Output * lista_file_carattere_1_svc(Input *, struct svc_req *);

#elif __STDC__
#define ELIMINA_OCCORRENZE ((rpc_uint)1)
extern  int * elimina_occorrenze_1(char *, CLIENT *);
extern  int * elimina_occorrenze_1_svc(char *, struct svc_req *);
#define LISTA_FILE_CARATTERE ((rpc_uint)2)
extern  Output * lista_file_carattere_1(Input *, CLIENT *);
extern  Output * lista_file_carattere_1_svc(Input *, struct svc_req *);

#else /* Old Style C */
#define ELIMINA_OCCORRENZE ((rpc_uint)1)
extern  int * elimina_occorrenze_1();
extern  int * elimina_occorrenze_1_svc();
#define LISTA_FILE_CARATTERE ((rpc_uint)2)
extern  Output * lista_file_carattere_1();
extern  Output * lista_file_carattere_1_svc();
#endif /* Old Style C */

#endif /* !_PELLEGRINO_LORENZO_0000971455_RPC_XFILE_H_RPCGEN */
