#!/bin/bash

#comando #dirin #string #ext #fout

cd "$1"

for file in *
do
    if [[ -f $file ]]; 
        then
            occorrenze=`grep -o $2 $file | wc -l`
            if [[ $occorrenze != 0 ]] && [[ $file = *$3 ]]
                then
                    dimensione=`stat -c %s $file`
                    proprietario=`ls -ls $file | cut -d " " -f4`
                    echo "`pwd`/$file:$dimensione:$proprietario:$occorrenze" >> $4
                    echo "`pwd`/$file -> $dimensione -> $proprietario -> $occorrenze    mandato in $4"
            fi
    elif [[ -d $file ]]
        then "$0" "$file" "$2" "$3" "$4"
    fi
done
