---

# 1) 
- name: installare il pacchetto snmpd
  ansible.builtin.apt:
    update_cache: yes
    name: snmpd

# 2) 
- name: Copia del file /etc/snmp/snmpd.conf per configurarlo
  ansible.builtin.copy:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  notify: Restart snmpd
