/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_nome (XDR *xdrs, nome objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, MAXNAMELENGHT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Riga (XDR *xdrs, Riga *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_nome (xdrs, objp->id))
			 return FALSE;
		 if (!xdr_nome (xdrs, objp->tipo))
			 return FALSE;
		 if (!xdr_nome (xdrs, objp->partenza))
			 return FALSE;
		 if (!xdr_nome (xdrs, objp->arrivo))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->hh))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mm))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ritardo))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->hh);
		IXDR_PUT_LONG(buf, objp->mm);
		IXDR_PUT_LONG(buf, objp->ritardo);
		}
		 if (!xdr_nome (xdrs, objp->audio))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_nome (xdrs, objp->id))
			 return FALSE;
		 if (!xdr_nome (xdrs, objp->tipo))
			 return FALSE;
		 if (!xdr_nome (xdrs, objp->partenza))
			 return FALSE;
		 if (!xdr_nome (xdrs, objp->arrivo))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->hh))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mm))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->ritardo))
				 return FALSE;

		} else {
		objp->hh = IXDR_GET_LONG(buf);
		objp->mm = IXDR_GET_LONG(buf);
		objp->ritardo = IXDR_GET_LONG(buf);
		}
		 if (!xdr_nome (xdrs, objp->audio))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_nome (xdrs, objp->id))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->tipo))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->partenza))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->arrivo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->hh))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mm))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ritardo))
		 return FALSE;
	 if (!xdr_nome (xdrs, objp->audio))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->corse, N,
		sizeof (nome), (xdrproc_t) xdr_nome))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dimL))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	 if (!xdr_nome (xdrs, objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->newRitardo))
		 return FALSE;
	return TRUE;
}
