/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_nome (XDR *xdrs, nome objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, MAX_LEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->ids, 6,
		sizeof (nome), (xdrproc_t) xdr_nome))
		 return FALSE;
	return TRUE;
}
